apiVersion: batch/v1
kind: CronJob
metadata:
  name: scb-api-leaf-updater
  labels:
    app: scb
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
      spec:
        template:
          spec:
            containers:
              - name: scb-api-leaf-updater
                image: scb-api-leaf-updater:v0.0.8
                ports:
                  - containerPort: 5555
                    protocol: TCP
            restartPolicy: Never
