apiVersion: batch/v1
kind: CronJob
metadata:
  name: scb-update-scheduler
  labels:
    app: scb
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scb-update-scheduler
              image: scb-update-scheduler:v0.0.5
              ports:
                - containerPort: 5555
                  protocol: TCP
          restartPolicy: Never
