apiVersion: batch/v1
kind: CronJob
metadata:
  name: scb-update-scheduler
  labels:
    app: scb
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
      spec:
        template:
          spec:
            containers:
              - name: scb-update-scheduler
                image: scb-update-scheduler:v0.0.4
                ports:
                  - containerPort: 5555
                    protocol: TCP
            restartPolicy: Never
